### ISSUE TITLE
Placeholder patterns not working when set from outside

### ISSUE THREAD

**Issue by nilsga** [belgattitude/pjbserver-tools#4]
`{base_dir}` and `{tcp_port}` is only expanded within `getDefaultConfig`. Setting them explicitly have no effect. The line https://github.com/belgattitude/pjbserver-tools/blob/master/src/PjbServer/Tools/StandaloneServer/Config.php#L80 merges the provided, non-expanded values.

**Comment by belgattitude** [comment]
Nice catch, I fixed it but realized the substitution of {tcp_port}/{base_dir} was not a great idea.

I've reworked the [default config file](https://github.com/belgattitude/pjbserver-tools/blob/master/config/pjbserver.config.php.dist#L12) to only rely on php variables... See also the updated [changelog](https://github.com/belgattitude/pjbserver-tools/blob/master/CHANGELOG.md)

But please keep in mind that if you decided to embed the standalone server in a sort of prestashop plugin, the directory used for keeping log and pid files should be the one of prestashop...
